Feature: Per-mutant test selection and directory run mode

  # TRACKING: Issue #15 — directory run mode + --test-contexts
  #
  # CONTRACT:
  #   command: mutate4py <file-or-dir> [--test-contexts PATH] [other flags]
  #   --test-contexts PATH — path to a .coverage SQLite db generated by
  #     pytest --cov-context=test; missing file exits 2 with clear error.
  #   directory run mode — when <file-or-dir> is a directory, iterate over
  #     all .py files and run mutations on each; exit non-zero if any file
  #     has survivors or errors.
  #   per-mutant test selection — when --test-contexts is set, for each mutant
  #     on line L, query the db for test node IDs covering L and run only those;
  #     fall back to full --test-command when no tests cover the line.
  #   parallelism override — when --test-contexts is set and --max-workers >= 2,
  #     run mode proceeds serially (parallel workers share a fixed test_command,
  #     extending _workers.py for per-mutant selection is out of scope).
  #
  # CONSTRAINTS:
  #   - --test-contexts PATH: missing file → exit 2, clear error to stderr.
  #   - Numbits decoding: byte N bit B → line N×8+B+1 (coverage.py v7+ format).
  #   - Context strings have |run (or similar) suffix stripped to yield node IDs.
  #   - Empty context strings (overall run, not per-test) are ignored.
  #   - When no tests cover a mutated line, run the full --test-command (no skip).
  #   - When --test-contexts is set and --max-workers >= 2, serial mode is used.
  #   - Directory run mode: exits non-zero if ANY file's run exits non-zero.
  #   - Directory run mode: skips __pycache__ directories.
  #
  # SEQUENCING:
  #   - --test-contexts validation occurs before any mutations run.
  #   - Per-mutant command: "{test_command} {node_id_1} {node_id_2} ..." when
  #     tests are found; "{test_command}" when no tests cover the line.
  #   - Directory run: files processed in sorted order; per-file run is serial.

  Scenario: --test-contexts missing file exits 2 with clear error
    Given a Python source file "src.py" containing "x = a > b"
    When mutate4py is run with "--test-contexts /nonexistent/.coverage"
    Then the exit code is 2
    And stderr contains "--test-contexts file not found"

  Scenario: directory run mode iterates over all .py files
    Given a directory "src/" containing two Python files "a.py" and "b.py"
    When mutate4py is run on the directory in scan mode
    Then the output contains two "Mutation scan:" lines

  Scenario: directory run mode exits non-zero if any file fails
    Given a directory "src/" containing Python files
    When mutate4py is run on the directory in run mode and one file has survivors
    Then the exit code is non-zero

  Scenario: --test-contexts with --max-workers >= 2 forces serial mode
    Given a Python source file with mutation sites covered by known tests
    And a .coverage db with per-test context data
    When mutate4py is run with "--test-contexts .coverage --max-workers 4"
    Then the run proceeds serially (no worker-N tokens in output)
